SELECT
		APPLY_DATE,
		CUSTOMER_CODE,
		PRODUCT_CODE,
		RETAIL_PRICE,
		CRE_FUNC,
		CRE_DATETM,
		CRE_USER,
		UPD_FUNC,
		UPD_DATETM,
		UPD_USER,
		DEL_FUNC,
		DEL_DATETM,
		DEL_USER
	FROM
		CUSTOMER_RETAIL_PRICE_/*$domainId*/
	ORDER by
		APPLY_DATE ASC, CUSTOMER_CODE ASC, PRODUCT_CODE ASC