SELECT
	PRICE.APPLY_DATE,
	PRICE.PRODUCT_CODE,
	PRICE.PRODUCT_NAME
FROM
	CUSTOMER_RETAIL_PRICE_/*$domainId*/ PRICE
		LEFT OUTER JOIN CUSTOMER_MST_/*$domainId*/ CST
			ON CUSTOMER_CODE = CST.CUSTOMER_CODE
		LEFT OUTER JOIN PRODUCT_MST_/*$domainId*/ PRO
			ON PRODUCT_CODE = PRO.PRODUCT_CODE
GROUP BY
	PRICE.APPLY_DATE,
	PRICE.PRODUCT_CODE
