SELECT
	PRICE.CUSTOMER_RETAIL_PRICE_ID,
	PRICE.APPLY_DATE,
	PRICE.CUSTOMER_CODE,
	CST.CUSTOMER_NAME,
	PRICE.PRODUCT_CODE,
	PRO.PRODUCT_NAME,
    PRICE.RETAIL_PRICE,
    (SELECT CATEGORY_CODE_NAME
       FROM CATEGORY_TRN_/*$domainId*/
      WHERE CATEGORY_ID = 39
        AND CATEGORY_CODE = PRO.TAX_CATEGORY) AS TAX_CATEGORY_NAME,
	PRICE.CRE_FUNC,
	PRICE.CRE_DATETM,
	PRICE.CRE_USER,
	PRICE.UPD_FUNC,
	PRICE.UPD_DATETM,
	PRICE.UPD_USER
FROM
	CUSTOMER_RETAIL_PRICE_/*$domainId*/ PRICE
		LEFT OUTER JOIN CUSTOMER_MST_/*$domainId*/ CST
			ON PRICE.CUSTOMER_CODE = CST.CUSTOMER_CODE
		LEFT OUTER JOIN PRODUCT_MST_/*$domainId*/ PRO
			ON PRICE.PRODUCT_CODE = PRO.PRODUCT_CODE
/*BEGIN*/
WHERE
	/*IF applyDate != null*/
	PRICE.APPLY_DATE = /*applyDate*/
	/*END*/
	/*IF customerCode != null*/
	AND PRICE.CUSTOMER_CODE = /*customerCode*/
	/*END*/
	/*IF productCode != null*/
	AND PRICE.PRODUCT_CODE = /*productCode*/
	/*END*/
/*END*/
/*BEGIN*/
ORDER BY
	/*IF sortColumnCustomerRetailPrice != null */
	/*$sortColumnCustomerRetailPrice*/
	/*END*/
	/*IF sortOrder != null*/
	/*$sortOrder*/
	/*END*/,
	PRICE.CUSTOMER_CODE,
	PRICE.PRODUCT_CODE
/*END*/